# Generated by Django 6.0.1 on 2026-02-18 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código do Cupom')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor do Prêmio (KZ)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Código de Sorteio',
                'verbose_name_plural': 'Códigos de Sorteio',
            },
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_won', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prêmio Ganho')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Uso')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.promocode', verbose_name='Código Usado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Sorteio',
                'verbose_name_plural': 'Histórico de Sorteios',
            },
        ),
        migrations.DeleteModel(
            name='RouletteSettings',
        ),
    ]
