# Generated by Django 6.0.1 on 2026-03-03 20:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_promocode_promocodeusage_delete_roulettesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Capital Investido')),
                ('ciclo_dias', models.IntegerField(verbose_name='Duração do Ciclo (Dias)')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('is_active', models.BooleanField(default=True, verbose_name='Poupança Ativa?')),
                ('is_redeemed', models.BooleanField(default=False, verbose_name='Já Resgatado?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Poupança Programada',
                'verbose_name_plural': 'Poupanças Programadas',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
